language: node_js
node_js:
- '8'
script:
- cd vis
- npm install
- npm run build
- mv index.html ..
- mv dist ..
- cd ..
- find . | grep -v "dist" | grep -v "index.html" | xargs rm
deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: C2ehjTgcqd416oLRvsjGdih9dBGQn+ov69+EFrdhQJ58hcJrTcNgXcqeUBMpeBQ+V6sWTJadY6qnQDKQeTCvDSUDbrUs728bTyKdwwXXz47T+Jge3zqPRUx26fFBBIoDBj+vk8C+fT0AHY+0zurHaENQzGk+kKMJDEbwQvf+7e+B6+4tx420N5hh7SNnLB3F/FloyUfYhx4xkjKdrGN11Ym9qg6eIme9eZGMDyR/o8iod0IoGAqtvaX6oOaRzDPdjWCl1a78pbN88Iw0IuhFMq8RBjMq0hQzYFDupT+Pop9iSAQjcp9U+tZ20gYrAezDW6ZAeSeJZejE/RUYBqThutQmaA1NwNaBnkrcDf7tO5v6mrQcpmSTsyN1a4qFjKnoC3y8r6hKQ4NexjiGctZO0A6OajpmNTWNRUQ8MilUdcLkb0gr1ndwR5/NgXO2HAJHlviU5f8wENhCNWuu3cAc6FACWlzhns7S7H+7jZMARvoPtLtbLpY4KWQfGRmu1MdI0oNWjYUUanpX/oRCbOFiwBggONX55gsoUb7g5GMgtbwIWONkShqWCvTRizF8CH+jCnfO95IzQvjawW8v+Js5E2xDymKORu4aLtGtYrbZrtELVJRen8H1JnX1zq4pHwjgcfesnHU0cl3yV7DptUygIhjlkHd4QTtkJVM2wivk+j4=
  keep-history: true
  on:
    branch: master
notifications:
  email: false
